import { createParamDecorator, type ExecutionContext } from '@nestjs/common';
import { isUUID } from 'class-validator';
import { type Request } from 'express';
import { validationError } from '../../kernel/domain-error';
import { DomainErrorException } from './domain-error.exception';

export const IDEMPOTENCY_KEY_HEADER = 'Idempotency-Key';
export const IDEMPOTENT_REPLAYED_HEADER = 'Idempotent-Replayed';

/** The key must be a UUID v4 generated by the client for each purchase; normalized to lower case. */
export function parseIdempotencyKey(value: string | undefined): string {
  if (value === undefined || !isUUID(value, '4')) {
    throw new DomainErrorException(
      validationError(IDEMPOTENCY_KEY_HEADER, 'header is required and must be a UUID v4'),
    );
  }
  return value.toLowerCase();
}

/** Reads and validates the `Idempotency-Key` header (400 when missing or invalid). */
export const IdempotencyKey = createParamDecorator((_data: unknown, context: ExecutionContext) =>
  parseIdempotencyKey(context.switchToHttp().getRequest<Request>().header(IDEMPOTENCY_KEY_HEADER)),
);
